application: ae-gallery
version: 1
runtime: go
api_version: go1

handlers:
- url: /admin/.*
  script: _go_app
  login: admin

- url: /public
  static_dir: public

- url: /.*
  script: _go_app

skip_files:
- node_modules/
