application: ae-gallery
version: 1
runtime: go
api_version: go1

handlers:
- url: /admin
  login: admin
  script: _go_app

- url: /admin/.+
  script: _go_app
  login: admin
  auth_fail_action: unauthorized

- url: /public
  static_dir: public

- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?node_modules/.*
